/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEmployee.java
 *
 * Created on Nov 19, 2013, 3:15:16 AM
 */

package farmmanagementsystem.gui.add;

import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.gui.UploadImage;
import farmmanagementsystem.model.Employee;
import farmmanagementsystem.model.User;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddEmployee extends javax.swing.JDialog {

    /** Creates new form AddEmployee */
    public AddEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        setLocationRelativeTo(null);
        generatedEmp_ID = DBQuery.generateEmpID();
        jLabelEmpID.setText(generatedEmp_ID+"");
    }

    public User user;
    private int generatedEmp_ID;
    private UploadImage.ImagePackage img;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldComments = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelEmpID = new javax.swing.JLabel();
        jButtonSAVE = new javax.swing.JButton();
        jButtonCANCEL = new javax.swing.JButton();
        jComboBoxGender = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelIMG = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldContactNo = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jCheckBoxDATA = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Employee");

        jLabel1.setText("Name:");

        jLabel2.setText("Address:");

        jLabel3.setText("Comments:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Employee ID:");

        jLabelEmpID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEmpID.setForeground(new java.awt.Color(204, 0, 0));
        jLabelEmpID.setText("100001");

        jButtonSAVE.setText("SAVE");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonCANCEL.setText("CANCEL");
        jButtonCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELActionPerformed(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel6.setText("Date of Birth:");

        dateChooserCombo1.setNothingAllowed(false);
        dateChooserCombo1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        dateChooserCombo1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateChooserCombo1OnSelectionChange(evt);
            }
        });

        jLabel7.setText("Age:");

        jLabelAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAge.setText("Age:");

        jLabelIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmmanagementsystem/images/POSITION.png"))); // NOI18N
        jLabelIMG.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setText("Contact No:");

        jButtonBrowse.setText("Browse>>");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jCheckBoxDATA.setText("NO DATA");
        jCheckBoxDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDATAActionPerformed(evt);
            }
        });

        jLabel9.setText("Employment Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonSAVE)
                .addGap(45, 45, 45)
                .addComponent(jButtonCANCEL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelEmpID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jButtonBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIMG))
                    .addComponent(jTextFieldComments, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldContactNo)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxDATA))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmpID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIMG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jButtonBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabelAge)
                        .addComponent(jCheckBoxDATA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSAVE)
                    .addComponent(jButtonCANCEL))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed
       if(!isValidFields()){
           JOptionPane.showMessageDialog(null, "Incomplete Data", "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(img == null){
          if(!confirm("NO IMAGE...\n PROCEED ANYWAY?")) {
               return;
           }
       }
       Employee e = new Employee();
       e.setEmp_id(generatedEmp_ID);
       e.setAddress(jTextFieldAddress.getText());
       e.setComments(jTextFieldComments.getText());
       e.setGender(jComboBoxGender.getSelectedItem()+"");
       e.setName(jTextFieldName.getText());
       //e.sethDate(dateChooserCombo2.toString());
       e.sethDate(dateChooserCombo2.getSelectedDate().getTime());
       if(!jCheckBoxDATA.isSelected()) {
            e.setbDate(dateChooserCombo1.getSelectedDate().getTime());
        }
       else {
            e.setbDate(new Date(0, 0, 1));
        }
       e.setContactNo(jTextFieldContactNo.getText());
       
       if(e.getAge()<15 && !jCheckBoxDATA.isSelected()){
        JOptionPane.showMessageDialog(null, "Employee must be 15 years old and above", "INVALID AGE", JOptionPane.ERROR_MESSAGE);
           return;
       }else if(jCheckBoxDATA.isSelected()){
           if(!confirm("NO DATA FOR BIRTHDATE..\n PROCEED ANYWAY?")) {
               return;
           }
       }
       if(DBQuery.isExistName(e.getName())){
        JOptionPane.showMessageDialog(null, "Name already exist", "DUPLICATION ERROR", JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(confirm("REGISTER NEW EMPLOYEE?")){
       DBQuery.addEmployee(e);
       if(img != null) {
               DBQuery.insertProfileImage(e.getEmp_id(), img.getThumbnail());
           }
       JOptionPane.showMessageDialog(null, "SAVED", "SAVED", JOptionPane.INFORMATION_MESSAGE);
       DBQuery.insertLog(user.getUser_id(), "REGISTER EMPLOYEE [Employee ID :"+e.getEmp_id()+"]");
       dispose();
        }
    }//GEN-LAST:event_jButtonSAVEActionPerformed

    private void jButtonCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELActionPerformed
        if(confirm("ARE YOU SURE TO CANCEL ACTION?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonCANCELActionPerformed

    private void dateChooserCombo1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnSelectionChange
            Employee e =new Employee();
            e.setbDate(dateChooserCombo1.getSelectedDate().getTime());
            jLabelAge.setText(e.getAge()+" years old");
    }//GEN-LAST:event_dateChooserCombo1OnSelectionChange

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        UploadImage uploader = new UploadImage(null, true);
        uploader.setVisible(true);
        UploadImage.ImagePackage tmp = uploader.getSelectedImage();
        if(tmp != null){
            img = tmp;
            jLabelIMG.setPreferredSize(new Dimension(img.getThumbnail().getWidth(),img.getThumbnail().getHeight()));
            jLabelIMG.setSize(new Dimension(img.getThumbnail().getWidth(),img.getThumbnail().getHeight()));
            jLabelIMG.setIcon(new ImageIcon(img.getThumbnail()));
        }
        else if(img == null) {
            jLabelIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmmanagementsystem/images/POSITION.png")));
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jCheckBoxDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDATAActionPerformed
        dateChooserCombo1.setVisible(!jCheckBoxDATA.isSelected());
        jLabelAge.setVisible(!jCheckBoxDATA.isSelected());
        jLabel7.setVisible(!jCheckBoxDATA.isSelected());
    }//GEN-LAST:event_jCheckBoxDATAActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEmployee dialog = new AddEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCANCEL;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JCheckBox jCheckBoxDATA;
    private javax.swing.JComboBox jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmpID;
    private javax.swing.JLabel jLabelIMG;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldComments;
    private javax.swing.JTextField jTextFieldContactNo;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    private boolean isValidFields(){
        if(jTextFieldAddress.getText().isEmpty() || jTextFieldName.getText().isEmpty() || dateChooserCombo2.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    private boolean confirm(String confirmMessage){
        int ans = JOptionPane.showConfirmDialog(this, confirmMessage, "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        return (ans == JOptionPane.YES_OPTION);
    }

}
