/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddGrossProfit.java
 *
 * Created on Nov 19, 2013, 11:30:22 AM
 */

package farmmanagementsystem.gui.add;


import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.model.Activity;
import farmmanagementsystem.model.Employee;
import farmmanagementsystem.model.Expenses;
import farmmanagementsystem.model.GrossProfit;
import farmmanagementsystem.model.Location;
import farmmanagementsystem.model.Salary;
import farmmanagementsystem.model.User;
import farmmanagementsystem.util.LookAndFeels;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class AddGrossProfit extends javax.swing.JDialog {

    /** Creates new form AddGrossProfit */
    public AddGrossProfit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        new LookAndFeels(this, 3);
        setLocationRelativeTo(null);
        if(!hasActivityPending())
            return;        
        jComboBoxLocation.setModel(new DefaultComboBoxModel(DBQuery.getLocationForGP().toArray()));
        jComboBoxLocation.setSelectedIndex(0);
        jComboBoxLocationItemStateChanged(null);
        jLabelMaintenancePerson.setText(((Location)jComboBoxLocation.getSelectedItem()).getCareTaker().getName());
        jLabelLocationAddress.setText(((Location)jComboBoxLocation.getSelectedItem()).getAddress());
        activity = DBQuery.getActivityOnLocation(((Location)jComboBoxLocation.getSelectedItem()), DBQuery.NOT_POSTED).get(0);
        setEmpList();
        generatedID = DBQuery.generateGrossProfitID();
        jLabelGP_ID.setText(""+generatedID);
    }
    public boolean invalid = false;
    private int generatedID;
    private Activity activity;
    public User user;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSAVE = new javax.swing.JButton();
        jButtonCANCEL = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldRemarks = new javax.swing.JTextField();
        jFormattedTextFieldGrossAmount = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabelMaintenanceShare = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocationAddress = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabelMaintenancePerson = new javax.swing.JLabel();
        jLabelActivityShare = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelGP_ID = new javax.swing.JLabel();
        jLabelOwnerShare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabelExpenses = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNET = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW GROSS PROFIT");

        jButtonSAVE.setText("SAVE");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonCANCEL.setText("CANCEL");
        jButtonCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jFormattedTextFieldGrossAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(#,##0.00)"))));
        jFormattedTextFieldGrossAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldGrossAmountActionPerformed(evt);
            }
        });
        jFormattedTextFieldGrossAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldGrossAmountFocusLost(evt);
            }
        });

        jLabel3.setText("Maintenance Share:");

        jLabel4.setText("Maintenance Person:");

        dateChooserCombo1.setFormat(2);

        jLabelMaintenanceShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelMaintenanceShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelMaintenanceShare.setText("0");

        jLabel2.setText("Gross Amount:");

        jLabelLocationAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocationAddress.setText("Vintar");

        jComboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLocationItemStateChanged(evt);
            }
        });

        jLabel12.setText("Remarks:");

        jLabelMaintenancePerson.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelMaintenancePerson.setText("Juan dela Cruz");

        jLabelActivityShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelActivityShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelActivityShare.setText("0");

        jLabel5.setText("Gross Profit ID:");

        jLabelGP_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGP_ID.setForeground(new java.awt.Color(204, 0, 0));
        jLabelGP_ID.setText("10101");

        jLabelOwnerShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelOwnerShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelOwnerShare.setText("0");

        jLabel1.setText("Location ID:");

        jLabel7.setText("Activity Share:");

        jLabel10.setText("Owner Share:");

        jLabel9.setText("Date Encoded:");

        jListEmpList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEmpList);

        jLabel6.setText("Expenses:");

        jLabelExpenses.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelExpenses.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExpenses.setText("0");

        jLabel8.setText("AMOUNT:");

        jLabelNET.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelNET.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNET.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGP_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMaintenancePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabelLocationAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRemarks))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelOwnerShare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMaintenanceShare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelActivityShare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldGrossAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jLabelNET, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGP_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLocationAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMaintenancePerson)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldGrossAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabelExpenses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabelNET))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMaintenanceShare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelActivityShare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOwnerShare))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Expenses"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Expense Date", "Reference", "Amount", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(100);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(1).setMinWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(120);
        jTable1.getColumnModel().getColumn(2).setMinWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(3).setMinWidth(170);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(170);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(170);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCANCEL)
                        .addGap(272, 272, 272))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSAVE)
                    .addComponent(jButtonCANCEL))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLocationItemStateChanged
        jLabelMaintenancePerson.setText(((Location)jComboBoxLocation.getSelectedItem()).getCareTaker().getName());
        jLabelLocationAddress.setText(((Location)jComboBoxLocation.getSelectedItem()).getAddress());
        activity = DBQuery.getActivityOnLocation(((Location)jComboBoxLocation.getSelectedItem()), DBQuery.NOT_POSTED).get(0);
        loadTable(activity.getLocation().getLoc_id());
        calculate();
        setEmpList();
}//GEN-LAST:event_jComboBoxLocationItemStateChanged

    private void jFormattedTextFieldGrossAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldGrossAmountFocusLost
        calculate();
    }//GEN-LAST:event_jFormattedTextFieldGrossAmountFocusLost

    private void jFormattedTextFieldGrossAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldGrossAmountActionPerformed
        jFormattedTextFieldGrossAmountFocusLost(null);;
    }//GEN-LAST:event_jFormattedTextFieldGrossAmountActionPerformed

    private void jButtonCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELActionPerformed
        if(confirm("ARE YOU SURE TO CANCEL ACTION?"))
        dispose();
    }//GEN-LAST:event_jButtonCANCELActionPerformed

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed

        if(!isValidField()){
            JOptionPane.showMessageDialog(null, "Invalid Data", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        GrossProfit gp = new GrossProfit();
        gp.setActivity_share(act_share);
        gp.setDate(dateChooserCombo1.getSelectedDate().getTime());
        gp.setGp_id(generatedID);
        gp.setGross_amount(gross);
        gp.setLocation((Location) jComboBoxLocation.getSelectedItem());
        gp.setMaintainer_share(CT_share);
        gp.setOwner_share(owner_share);
        gp.setRemarks(jTextFieldRemarks.getText());
        gp.setActivity(activity);
        if(confirm("SAVE NEW GROSS PROFIT ENTRY?")){
            DBQuery.addGrossProfit(gp);
            toSalary();//call for computaion of salary
            postingExpenses();
            DBQuery.insertLog(user.getUser_id(), "GROSS PROFIT ENTRY [GP ID:"+gp.getGp_id()+"]");
            dispose();
        }
    }//GEN-LAST:event_jButtonSAVEActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddGrossProfit dialog = new AddGrossProfit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButtonCANCEL;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JComboBox jComboBoxLocation;
    private javax.swing.JFormattedTextField jFormattedTextFieldGrossAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActivityShare;
    private javax.swing.JLabel jLabelExpenses;
    private javax.swing.JLabel jLabelGP_ID;
    private javax.swing.JLabel jLabelLocationAddress;
    private javax.swing.JLabel jLabelMaintenancePerson;
    private javax.swing.JLabel jLabelMaintenanceShare;
    private javax.swing.JLabel jLabelNET;
    private javax.swing.JLabel jLabelOwnerShare;
    private javax.swing.JList jListEmpList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldRemarks;
    // End of variables declaration//GEN-END:variables

    private double gross=0,act_share,CT_share,owner_share;

    private boolean hasActivityPending(){
        if(DBQuery.getLocationForGP().isEmpty()){
           JOptionPane.showMessageDialog(null, "NO ACTIVITY AVAILABLE", "EMPTY DATA", JOptionPane.ERROR_MESSAGE);
           invalid = true;
           return false;
        }
        return true;
    }

    private void calculate(){
        if(!jFormattedTextFieldGrossAmount.getText().isEmpty()){
            Location l = (Location)jComboBoxLocation.getSelectedItem();
             gross = Double.parseDouble(jFormattedTextFieldGrossAmount.getText().replaceAll(",", ""));
//             act_share = activity.getAct_share(gross-totalExpense);
//             CT_share = (l.getMaintenance_Share(gross-totalExpense));
             act_share = activity.getAct_share(gross);
             CT_share = (l.getMaintenance_Share(gross));
             //owner_share = (gross-totalExpense)-(totalExpense+act_share+CT_share);
             owner_share = (gross)-(totalExpense+act_share+CT_share);
             jLabelNET.setText(String.format( "%,.2f",gross));
             jLabelActivityShare.setText(String.format( "%,.2f",act_share)+" ("+activity.getAct_share()+"%)");
             jLabelMaintenanceShare.setText(String.format( "%,.2f",CT_share)+" ("+l.getMaintenance_share()+"%)");
             jLabelOwnerShare.setText(String.format( "%,.2f",owner_share));
        }
    }
    private void setEmpList(){
        jListEmpList.setListData(DBQuery.getEmployeeOnActivity(activity.getAct_id()).toArray());
    }


    private boolean isValidField(){
        if(jFormattedTextFieldGrossAmount.getText().isEmpty() ||jTextFieldRemarks.getText().isEmpty())
            return false;
        if(Double.parseDouble(jFormattedTextFieldGrossAmount.getText().replaceAll(",", ""))<0){
            return false;
        }
        if(dateChooserCombo1.getSelectedDate().getTime().after(new Date())){
            JOptionPane.showMessageDialog(null, "Date Must Not Be Future", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean confirm(String confirmMessage){
        int ans = JOptionPane.showConfirmDialog(this, confirmMessage, "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        return (ans == JOptionPane.YES_OPTION);
    }
//computation of salary
    private void toSalary(){
        ListModel li = jListEmpList.getModel();
        
        double individualShare = act_share/li.getSize();
//computation for activity share
        for(int i = 0; i<li.getSize();i++){
            Employee e = (Employee) li.getElementAt(i);
            Salary s = new Salary();
            s.setAmount(individualShare);
            s.setEmpID(e.getEmp_id());
            s.setGp_id(generatedID);
            s.setRemarks("Activity Share");
            DBQuery.addSalary(s);
        }
        //computation for maintainer
        activity.setPosted(true);
        DBQuery.updateActivity(activity);
        Employee CT = ((Location) jComboBoxLocation.getSelectedItem()).getCareTaker();
        Salary ct = new Salary();
        ct.setAmount(CT_share);
        ct.setEmpID(CT.getEmp_id());
        ct.setGp_id(generatedID);
        ct.setRemarks("Maintenance Share");
        DBQuery.addSalary(ct);
    }

    private void postingExpenses(){
        for(Expenses e:expList){
            e.setGp_id(generatedID);
            e.setPosted(true);
            DBQuery.deleteExpenses(e.getExp_id());
            DBQuery.addExpense(e);
        }
    }

    private ArrayList<Expenses> expList;
    private double totalExpense = 0;
    private void loadTable(int loc_id){
        expList = DBQuery.getExpenses(loc_id);
        double total =0;
        for(int i=0; i<expList.size();i++){
            if(expList.get(i).getGp_id() != 0){
                expList.remove(i--);
                continue;
            }
            total += expList.get(i).getAmount();
        }
        totalExpense = total;
        jLabelExpenses.setText(String.format( "%,.2f",total));
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        tbl.setRowCount(0);
        for(Expenses e:expList){
            tbl.addRow(new Object[]{String.format("%1$ta, %1$tb %1$te, %1$tY", e.getDate()),e.getReference(),e.getAmount(),e.getRemarks()});
        }
    }
}
