/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * GUI_LOG_IN.java
 *
 * Created on Sep 13, 2013, 7:12:14 AM
 */
package farmmanagementsystem.gui;

import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.model.User;
import farmmanagementsystem.util.Breaker;
import farmmanagementsystem.util.LookAndFeels;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JDialog {

    private int ikey;
    private Component comp;

    public boolean isAccepted = false;

    /**
     * Creates new form GUI_LOG_IN
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        new LookAndFeels(this, 3);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        new Breaker(new Date());
        jPanel1 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextFielduserID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login [Farm Management System]");

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOK.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButtonOK.setMnemonic('E');
        jButtonOK.setText("Enter");
        jButtonOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOK.setOpaque(false);
        jButtonOK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 35));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 14));

        jPasswordFieldPassword.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, 260, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 56, -1, 14));

        jTextFielduserID.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel1.add(jTextFielduserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 71, 260, 30));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 250));
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(372, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (isFound()) {
            isAccepted = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "ACCOUNT NOT FOUND", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jPasswordFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyPressed
        ikey = evt.getKeyCode();
        comp = evt.getComponent();
        if (ikey == KeyEvent.VK_ENTER) {
            if (isFound()) {
                isAccepted = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "ACCOUNT NOT FOUND", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jPasswordFieldPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFielduserID;
    // End of variables declaration//GEN-END:variables

    public User user;

    private boolean isFound() {
        String user_id = jTextFielduserID.getText(), pw = jPasswordFieldPassword.getText();
        User tmp = DBQuery.getUser(user_id, pw);
        if (tmp != null) {
            user = tmp;
            DBQuery.insertLog(user_id, "LOG IN");
            return true;
        }
        return false;
    }
}
