/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageEmpoyee.java
 *
 * Created on Nov 19, 2013, 8:41:41 PM
 */

package farmmanagementsystem.gui;

import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.gui.add.AddEmployee;
import farmmanagementsystem.gui.update.UpdateEmployee;
import farmmanagementsystem.model.Employee;
import farmmanagementsystem.model.User;
import farmmanagementsystem.util.ImageRenderer;
import farmmanagementsystem.util.Print;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageEmpoyee extends javax.swing.JDialog {

    /** Creates new form ManageEmpoyee */
    public ManageEmpoyee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadTable();
    }

    public User user;
    private ArrayList<Employee> list;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonUPDATE = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldtxt = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANAGE EMPLOYEES");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Address", "Gender", "Birthdate", "Age", "Comments", "Contact No", "Date Employed", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(100);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(80);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setMinWidth(70);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(5).setMinWidth(40);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setMinWidth(120);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        jButton1.setText("ADD Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonUPDATE.setText("UPDATE Employee");
        jButtonUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPDATEActionPerformed(evt);
            }
        });

        jButtonPrint.setText("PRINT LIST");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabel1.setText("SEARCH BY NAME");

        jButtonSearch.setText("SEARCH");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUPDATE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonUPDATE)
                    .addComponent(jButtonPrint)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPDATEActionPerformed
        if(jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(rootPane, "NO SELECTED ITEM", "EMPTY SELECTION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UpdateEmployee up = new UpdateEmployee(null, true);
        up.setEmployee(list.get(jTable1.getSelectedRow()));
        up.user = user;
        up.setVisible(true);
        loadTable();
    }//GEN-LAST:event_jButtonUPDATEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddEmployee Ae = new AddEmployee(null, true);
        Ae.user = user;
        Ae.setVisible(true);
        loadTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        printEmp();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
       String txt = jTextFieldtxt.getText();
       if (txt.isEmpty())
           loadTable();
       else
       loadTablebyName(txt);
       
       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageEmpoyee dialog = new ManageEmpoyee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldtxt;
    // End of variables declaration//GEN-END:variables

    private void loadTable(){
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        jTable1.getColumnModel().getColumn(9).setCellRenderer(new ImageRenderer());
        tbl.setRowCount(0);
        list = DBQuery.getEmployee();
        for(Employee e: list){
            String date = String.format("%1$tb %1$td, %1$tY\n",e.getbDate());
            String hdate = String.format("%1$tb %1$td, %1$tY\n",e.gethDate());
            ImageRenderer.docOBJECT d = new ImageRenderer().getInstance(DBQuery.getProfileImage(e.getEmp_id()), "");
            tbl.addRow(new Object[]{e.getEmp_id(),e.getName(),e.getAddress(),e.getGender(),date,(e.getAge()<0?"N/A":e.getAge())
                    ,e.getComments(),e.getContactNo(), hdate, d});
        }
    }
    private void loadTablebyName(String txt){
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        jTable1.getColumnModel().getColumn(9).setCellRenderer(new ImageRenderer());
        tbl.setRowCount(0);
        list = DBQuery.getEmployeebyName(txt);
         for(Employee e: list){
            String date = String.format("%1$tb %1$td, %1$tY\n",e.getbDate());
            String hdate = String.format("%1$tb %1$td, %1$tY\n",e.gethDate());
            ImageRenderer.docOBJECT d = new ImageRenderer().getInstance(DBQuery.getProfileImage(e.getEmp_id()), "");
            tbl.addRow(new Object[]{e.getEmp_id(),e.getName(),e.getAddress(),e.getGender(),date,(e.getAge()<0?"N/A":e.getAge())
                    ,e.getComments(),e.getContactNo(), hdate,d});
        }
    }

    public void printEmp(){
         Print pp = new Print();
         String header = "(center)(bold)CALVEZ FARM\n"
                      +"(center)(bold)Worker Information System \n\n"
                      +"(center)(bold)"+"EMPLOYEES LIST"+"\n\n"
                      +"(center)"+ "As of " +String.format( "%1$TB %1$Td, %1$TY\n", new Date() )+"\n"
           +"(bold)No. of Results:(tab)"+list.size()+"\n";
         header += "NOTE:__________________________________________________________________\n";

         pp.setHeaderText(header);
         pp.showPreview(jTable1,this);
    }
}
