/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageLocation.java
 *
 * Created on Nov 20, 2013, 4:28:49 PM
 */

package farmmanagementsystem.gui;


import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.gui.add.AddLocation;
import farmmanagementsystem.gui.update.UpdateLocation;
import farmmanagementsystem.model.Location;
import farmmanagementsystem.model.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageLocation extends javax.swing.JDialog {

    /** Creates new form ManageLocation */
    public ManageLocation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadTable();
    }
    private ArrayList<Location> list;

    public User user;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLoc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Location");

        jTableLoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location ID", "Address", "Maintainer", "Maintenance Share", "Area Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLoc.setRowHeight(25);
        jTableLoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableLoc.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLoc);
        if (jTableLoc.getColumnModel().getColumnCount() > 0) {
            jTableLoc.getColumnModel().getColumn(0).setMinWidth(80);
            jTableLoc.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableLoc.getColumnModel().getColumn(1).setMinWidth(200);
            jTableLoc.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableLoc.getColumnModel().getColumn(2).setMinWidth(200);
            jTableLoc.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTableLoc.getColumnModel().getColumn(3).setMinWidth(120);
            jTableLoc.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTableLoc.getColumnModel().getColumn(4).setMinWidth(200);
            jTableLoc.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jButton1.setText("NEW LOCATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE LOCATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddLocation al = new AddLocation(null, true);
        al.user=user;
        al.setVisible(true);
        loadTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTableLoc.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "NO SELECTED ITEM","EMPTY SELECTION" ,JOptionPane.ERROR_MESSAGE);
            return;
        }
        UpdateLocation ul = new UpdateLocation(null, true);
        ul.user = user;
        ul.setLocation(list.get(jTableLoc.getSelectedRow()));
        ul.setVisible(true);
        loadTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageLocation dialog = new ManageLocation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLoc;
    // End of variables declaration//GEN-END:variables

    private void loadTable(){
        list = DBQuery.getLocation();
        DefaultTableModel tbl = (DefaultTableModel) jTableLoc.getModel();
        tbl.setRowCount(0);
        for(Location l:list){
            tbl.addRow(new Object[]{l.getLoc_id(),l.getAddress(),l.getCareTaker(),(l.getMaintenance_share()+"%"),l.getDescription()});
        }
    }
}
