/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewLogRecord.java
 *
 * Created on Nov 13, 2013, 6:59:37 PM
 */

package farmmanagementsystem.gui.view;


import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.model.Log;
import farmmanagementsystem.model.User;
import farmmanagementsystem.util.LookAndFeels;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ViewLogRecord extends javax.swing.JDialog {

    /** Creates new form ViewLogRecord */
    public ViewLogRecord(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        LookAndFeels LF = new LookAndFeels(this, 3);
        initComponents();
        setLocationRelativeTo(null);
        list = DBQuery.getLog(0, "", new Date(), new Date());
        loadTable();
    }

    private User user;

    public void setUser(User user) {
        this.user = user;
    }
    private String Condition = "ALL ITEM";

    private ArrayList<Log>list;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategory = new javax.swing.JComboBox();
        jTextFieldVal = new javax.swing.JTextField();
        jButtonSEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateChooserComboFROM = new datechooser.beans.DateChooserCombo();
        dateChooserComboTO = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log Viewer");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User ID", "Name", "Activity" }));

        jButtonSEARCH.setText("SEARCH");
        jButtonSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSEARCHActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "TIME", "User ID", "Name", "Activity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(100);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(450);

        dateChooserComboFROM.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        dateChooserComboTO.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        jLabel1.setText("FROM:");

        jLabel2.setText("TO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldVal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSEARCH)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserComboFROM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserComboTO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserComboTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserComboFROM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonSEARCH))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Date from = new Date();
        Date to  = new Date();

    private void jButtonSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSEARCHActionPerformed
         from = dateChooserComboFROM.getSelectedDate().getTime();
         to  = dateChooserComboTO.getSelectedDate().getTime();
        if(from.after(to)){
            JOptionPane.showMessageDialog(null, "INVALID RANGE OF DATE", "INVALID DATE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            list = DBQuery.getLog(jComboBoxCategory.getSelectedIndex(), jTextFieldVal.getText(), from, to);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewLogRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        Condition = "LOG that contains ['"+jTextFieldVal.getText()+"'] on user's "+jComboBoxCategory.getSelectedItem();
        loadTable();
    }//GEN-LAST:event_jButtonSEARCHActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewLogRecord dialog = null;
                try {
                    dialog = new ViewLogRecord(new javax.swing.JFrame(), true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewLogRecord.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserComboFROM;
    private datechooser.beans.DateChooserCombo dateChooserComboTO;
    private javax.swing.JButton jButtonSEARCH;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldVal;
    // End of variables declaration//GEN-END:variables

    private void loadTable(){
                
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();  
        tbl.setRowCount(0);
        for(int i=0; i<list.size();i++){
            Log tmp = list.get(i);
            String date = String.format( "%1$tb %1$te, %1$TY\n",tmp.getLog_date());
            String time = String.format( "%tr\n", tmp.getLog_date() );
            String time1 = time.substring(0, 5),time2 = time.substring(8, 11);
            //tbl.addRow(new Object[]{tmp.getLog_id(),date,time1+time2,tmp.getUser().getUser_id(),tmp.getUser().getName(),tmp.getActivity()});
            tbl.addRow(new Object[]{date,time1+time2,tmp.getUser().getUser_id(),tmp.getUser().getName(),tmp.getActivity()});
        }
    }

    
}
