/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddGrossProfit.java
 *
 * Created on Nov 19, 2013, 11:30:22 AM
 */

package farmmanagementsystem.gui.update;


import farmmanagementsystem.db.DBQuery;
import farmmanagementsystem.model.Activity;
import farmmanagementsystem.model.Expenses;
import farmmanagementsystem.model.GrossProfit;
import farmmanagementsystem.model.User;
import farmmanagementsystem.util.LookAndFeels;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class UpdateGrossProfit extends javax.swing.JDialog {

    /** Creates new form AddGrossProfit */
    public UpdateGrossProfit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel13.setVisible(false);
        jLabelNET.setVisible(false);
        new LookAndFeels(this, 3);
        setLocationRelativeTo(null);
    }  
    private Activity activity;
    private GrossProfit grossProfit;
    public User user;

    public void setGrossProfit(GrossProfit grossProfit) {
        viewOnly = DBQuery.isGP_Claimed(grossProfit.getGp_id());
        this.grossProfit = grossProfit;
        setGrossProfit();
        loadTable();
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSAVE = new javax.swing.JButton();
        jButtonCANCEL = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldRemarks = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMaintenanceShare = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocationAddress = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelMaintenancePerson = new javax.swing.JLabel();
        jLabelActivityShare = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelGP_ID = new javax.swing.JLabel();
        jLabelOwnerShare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelLocationGrossAmount = new javax.swing.JLabel();
        jLabelLocationID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpList = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();
        jLabelEXPENSES = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelNET = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE GROSS PROFIT");

        jButtonSAVE.setText("Update Remarks");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonCANCEL.setText("Close");
        jButtonCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("Maintenance Share:");

        jLabel4.setText("Maintenance Person:");

        jLabelMaintenanceShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelMaintenanceShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelMaintenanceShare.setText("0");

        jLabel2.setText("Gross Amount:");

        jLabelLocationAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocationAddress.setText("(Address)");

        jLabel12.setText("Remarks:");

        jLabelMaintenancePerson.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelMaintenancePerson.setText("(Maintainer)");

        jLabelActivityShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelActivityShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelActivityShare.setText("0");

        jLabel5.setText("Gross Profit ID:");

        jLabelGP_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGP_ID.setForeground(new java.awt.Color(204, 0, 0));
        jLabelGP_ID.setText("10101");

        jLabelOwnerShare.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelOwnerShare.setForeground(new java.awt.Color(102, 102, 255));
        jLabelOwnerShare.setText("0");

        jLabel1.setText("Location ID:");

        jLabel7.setText("Activity Share:");

        jLabel10.setText("Owner Share:");

        jLabel9.setText("Date:");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDate.setText("Kabacan Cotabato");

        jLabelLocationGrossAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocationGrossAmount.setText("(Amount)");

        jLabelLocationID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocationID.setText("10101");

        jListEmpList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEmpList);

        jLabel11.setText("EXPENSES:");

        jLabelEXPENSES.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelEXPENSES.setForeground(new java.awt.Color(255, 51, 51));
        jLabelEXPENSES.setText("0");

        jLabel13.setText("NET:");

        jLabelNET.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelNET.setForeground(new java.awt.Color(102, 102, 255));
        jLabelNET.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelOwnerShare, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGP_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLocationID)
                                    .addComponent(jLabel4))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLocationAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMaintenancePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelEXPENSES, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelLocationGrossAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelActivityShare, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabelMaintenanceShare, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNET, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGP_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelLocationID)
                            .addComponent(jLabelLocationAddress))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMaintenancePerson)
                        .addComponent(jLabel4)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelLocationGrossAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEXPENSES)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelNET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMaintenanceShare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelActivityShare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOwnerShare)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Expenses"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Expense Date", "Reference", "Amount", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCANCEL)
                        .addGap(272, 272, 272))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSAVE)
                    .addComponent(jButtonCANCEL))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELActionPerformed
        if(confirm("ARE YOU SURE TO CANCEL ACTION?"))
        dispose();
    }//GEN-LAST:event_jButtonCANCELActionPerformed

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed
             if(jTextFieldRemarks.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null, "EMPTY REMARKS!", "INVALID DATA", JOptionPane.ERROR_MESSAGE);
                 return;
             }
             if(grossProfit.getRemarks().equalsIgnoreCase(jTextFieldRemarks.getText())){
                 JOptionPane.showMessageDialog(null, "NO CHANGES MADE!", "NO CHANGES", JOptionPane.ERROR_MESSAGE);
                 return;
             }
            grossProfit.setRemarks(jTextFieldRemarks.getText());
            DBQuery.updateGrossProfitRemarks(jTextFieldRemarks.getText(), grossProfit.getGp_id());
            JOptionPane.showMessageDialog(null, "UPDATED", "UPDATES", JOptionPane.INFORMATION_MESSAGE);
            DBQuery.insertLog(user.getUser_id(), "GROSS PROFIT UPDATE [GP ID: "+grossProfit.getGp_id()+"]");
            dispose();
    }//GEN-LAST:event_jButtonSAVEActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateGrossProfit dialog = new UpdateGrossProfit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCANCEL;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActivityShare;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEXPENSES;
    private javax.swing.JLabel jLabelGP_ID;
    private javax.swing.JLabel jLabelLocationAddress;
    private javax.swing.JLabel jLabelLocationGrossAmount;
    private javax.swing.JLabel jLabelLocationID;
    private javax.swing.JLabel jLabelMaintenancePerson;
    private javax.swing.JLabel jLabelMaintenanceShare;
    private javax.swing.JLabel jLabelNET;
    private javax.swing.JLabel jLabelOwnerShare;
    private javax.swing.JList jListEmpList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldRemarks;
    // End of variables declaration//GEN-END:variables

    private double gross=0,act_share,CT_share,owner_share;

    private String calculatePercentage(double share,double gross){
        return String.format( "%,.2f",(share/gross)*100);
    }

    public boolean viewOnly = false;
    private void setGrossProfit(){
        jLabelGP_ID.setText(grossProfit.getGp_id()+"");
        jLabelDate.setText(String.format( "%1$tb %1$td, %1$tY\n",grossProfit.getDate()));
        jLabelLocationID.setText(grossProfit.getLocation().getLoc_id()+"");
        jLabelLocationAddress.setText(grossProfit.getLocation().getAddress());
        jLabelMaintenancePerson.setText(grossProfit.getLocation().getCareTaker().getName());
             gross = grossProfit.getGross_amount();
             act_share = grossProfit.getActivity_share();
             CT_share = grossProfit.getMaintainer_share();
             owner_share = grossProfit.getOwner_share();
             jLabelActivityShare.setText(String.format( "%,.2f",act_share)+" ("+calculatePercentage(act_share, gross)+"%)");
             jLabelMaintenanceShare.setText(String.format( "%,.2f",CT_share)+" ("+calculatePercentage(CT_share, gross)+"%)");
             jLabelOwnerShare.setText(String.format( "%,.2f",owner_share));
             jLabelNET.setText(String.format( "%,.2f",owner_share));
        jTextFieldRemarks.setText(grossProfit.getRemarks());
        jListEmpList.setListData(DBQuery.getEmployeeOnActivity(grossProfit.getActivity().getAct_id()).toArray());
        jLabelLocationGrossAmount.setText(String.format( "%,.2f",grossProfit.getGross_amount()));
        jButtonSAVE.setEnabled(!viewOnly);
        jTextFieldRemarks.setEditable(!viewOnly);
    }

    private boolean confirm(String confirmMessage){
        int ans = JOptionPane.showConfirmDialog(this, confirmMessage, "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        return (ans == JOptionPane.YES_OPTION);
    }


    private ArrayList<Expenses> expList;
    private double totalExpense = 0;
    private void loadTable(){
        expList = DBQuery.getExpensesByGP_ID(grossProfit.getGp_id());
        double total =0;
        for(int i=0; i<expList.size();i++){
            total += expList.get(i).getAmount();
        }
        totalExpense = total;
        jLabelEXPENSES.setText(String.format( "%,.2f",total));
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        tbl.setRowCount(0);
        for(Expenses e:expList){
            tbl.addRow(new Object[]{String.format("%1$ta, %1$tb %1$te, %1$tY", e.getDate()),e.getReference(),e.getAmount(),e.getRemarks()});
        }
    }
}
